### ISSUE TITLE
Only One User

### ISSUE THREAD

**Issue by botsonthego** [pfefferle/wordpress-ostatus#13]
At the moment only the owner of the site has a federated username botsonthego@botsonthego.xyz and this is the only one that will post to federated site when they post 

I want to have more users or all my users to have a username@botsonthego.xyz for federation because I have a person on the site that writes our blog posts, and even if they can't have there own username but have the main username show the posts when they post

is this possible and if so how do I set it up please

**Comment by pfefferle** [comment]
OStatus provides a federated user for all authors of a WordPress blog. It is exactly like you requested it: username@domain.tld

**Comment by pfefferle** [comment]
The user can find his federation username in the user settings.

**Comment by botsonthego** [comment]
But is not doing that As owner I am the only one that has a username@botsonthego.xyz and sites like mastodon only update when I post

![Capture](https://user-images.githubusercontent.com/77725279/105162917-21840480-5b0b-11eb-9417-250b7e73d48a.PNG)
![Capture](https://user-images.githubusercontent.com/77725279/105163052-4ed0b280-5b0b-11eb-9c6a-6ff675370bac.PNG)
![Capture](https://user-images.githubusercontent.com/77725279/105163304-a66f1e00-5b0b-11eb-9632-fc7b2aab240e.PNG)
![Capture](https://user-images.githubusercontent.com/77725279/105163366-bbe44800-5b0b-11eb-86ea-38c2363055dd.PNG)

**Comment by pfefferle** [comment]
Do you really use the OStatus plugin? Mastodon does not support OStatus, since month.

**Comment by botsonthego** [comment]
yes I am using it and no I did not know that thanks for the update

**Comment by pfefferle** [comment]
I think you are (also) using the ActivityPub plugin?!?

**Comment by botsonthego** [comment]
yes I am using that also

**Comment by pfefferle** [comment]
I just checked the profile page of the other author you mentioned and it seems really broken:

```
curl "https://botsonthego.xyz/author/leonlagrey/" \
     -H 'Accept: application/activity+json'
```

```JSON
  "name": "",
  "summary": "",
  "preferredUsername": "",
  "url": "https:\/\/botsonthego.xyz\/author\/",
```

The values are empty and the author page seems broken.

**Comment by botsonthego** [comment]
ok so how would I go about fixing this

**Comment by pfefferle** [comment]
it seems that the author has no username? how have you created it?

**Comment by pfefferle** [comment]
try to add the missing properties, like username, name, ...

**Comment by botsonthego** [comment]
ok this may be when we migrated the site over and did it manually to our new host, but it was created on our last host, and it was created when I invited them to the site

**Comment by botsonthego** [comment]
my host provider is asking where you found this error

**Comment by pfefferle** [comment]
the plugin does not find the informations. you can check what the plugin sees with the following request:

```
curl "https://botsonthego.xyz/author/leonlagrey/" \
     -H 'Accept: application/activity+json'
```

**Comment by botsonthego** [comment]
ok thanks

**Comment by pfefferle** [comment]
can you login as that user?

**Comment by pfefferle** [comment]
maybe you try to login and check the author settings.

**Comment by botsonthego** [comment]
yes I can log in

**Comment by pfefferle** [comment]
Hmm, your site seems a bit broken. the author page shows the JSON instead of HTML: https://botsonthego.xyz/author/admin/

**Comment by botsonthego** [comment]
and in his settings all the info is showing up and he even shows 

leonlagrey@botsonthego.xyz in his profile it just wont show on sites like mastodon but as u said oststus does not work there any more 

is there another site I can test this on

**Comment by pfefferle** [comment]
No, the JSON is broken, so it does not work. It is not a problem of mastodon.

**Comment by botsonthego** [comment]
my host is asking what server settings are required for the plugin

**Comment by pfefferle** [comment]
it seems to be no hosting problem. the functionality works, it is only that some wordpress core functions do not return what they should return.

**Comment by pfefferle** [comment]
it seems no hosting problem, because it works properly for the main user.

**Comment by botsonthego** [comment]
ok cool

**Comment by pfefferle** [comment]
do you use a caching plugin or has your hoster enabled caching?

**Comment by botsonthego** [comment]
I use WP-Rocket that has caching clearer

**Comment by pfefferle** [comment]
Maybe you try to clear the cache?

**Comment by botsonthego** [comment]
so it can find leonlagrey on friendica just does not link to the correct page for that user on the site

**Comment by botsonthego** [comment]
> Maybe you try to clear the cache?

done that one of the first things I thought of before contacting you

**Comment by pfefferle** [comment]
friendica does support OStatus, so maybe it uses OStatus instead of ActivityPub there.

**Comment by botsonthego** [comment]
ok thanks for your help, it looks like it may be activitypub then that's the problem and I will contact them and see what I can do bit thanks for your time and help today it is much appreciated

**Comment by pfefferle** [comment]
it is also me ;)

**Comment by pfefferle** [comment]
But sure, it seems to be no OStatus problem so we can move the discussion to the AP plugin repo. See you there ;)
