### ISSUE TITLE
Only content with gnu-social/mastodon

### ISSUE THREAD

**Issue by nicolascluz** [pfefferle/wordpress-ostatus#4]
Hy, I have some problems to display post. On mastodon, i had full content and summary in tham time. I just made a copy of feed-atom.php without summary (and remove title with)
Ps: oooh my english .. m*rde

**Comment by pfefferle** [comment]
pas de problème :)

I am don't like the current representation of blogposts in mastodon.

Your problem is that you do not like the short preview with the "read more" at all, or is it how the short abstract looks like?

**Comment by nicolascluz** [comment]
Yep , i found a simply stupid solution. 
Just copy feed-atom.php to feed-atom-2.php , remove summary / title and change name in plugin
It 's working  .. 😓

**Comment by pfefferle** [comment]
Good point... I will clone the feed and add some options to en/disable the summary or to only use the summary.

**Comment by pfefferle** [comment]
hmmm. Perhaps I should add a different feed template and add some options to customize it.

good point.

**Comment by pfefferle** [comment]
@nicolascluz I just saw your nice custom/child theme for sempress... do you have released it into public? I would love to link it on the SemPress readme!

**Comment by pfefferle** [comment]
I updated the theme and made the `summary` configurable
